// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Simurgh.DAL;

namespace Simurgh.DAL.Migrations
{
    [DbContext(typeof(SimurghDB))]
    partial class SimurghDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("Simurgh.DAL.Model.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Avatar");

                    b.Property<string>("ClientDescription");

                    b.Property<string>("ClientName");

                    b.Property<string>("GoogleMapAddress");

                    b.Property<int?>("RowNo")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Simurgh.DAL.Model.Picture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ClientId");

                    b.Property<int?>("ProjectId");

                    b.Property<int>("Type");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Pictures");
                });

            modelBuilder.Entity("Simurgh.DAL.Model.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal?>("AcctualMoneySpent");

                    b.Property<int?>("ClientId");

                    b.Property<DateTime?>("Created");

                    b.Property<string>("Description");

                    b.Property<decimal?>("EvaluationAmount");

                    b.Property<DateTime?>("EvaluationDate");

                    b.Property<DateTime?>("ExecutionStarted");

                    b.Property<DateTime?>("Finished");

                    b.Property<string>("GoogleMapAddress");

                    b.Property<DateTime?>("LastUpdated");

                    b.Property<decimal?>("MoneyRaised");

                    b.Property<string>("Name");

                    b.Property<int?>("ProjectStage");

                    b.Property<int?>("RowNo")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Simurgh.DAL.Model.Subscriber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("EMail");

                    b.Property<string>("FirstName");

                    b.HasKey("Id");

                    b.HasIndex("EMail")
                        .IsUnique();

                    b.ToTable("Subscribers");
                });

            modelBuilder.Entity("Simurgh.DAL.Model.Picture", b =>
                {
                    b.HasOne("Simurgh.DAL.Model.Client")
                        .WithMany("Pictures")
                        .HasForeignKey("ClientId");

                    b.HasOne("Simurgh.DAL.Model.Project")
                        .WithMany("Pictures")
                        .HasForeignKey("ProjectId");
                });

            modelBuilder.Entity("Simurgh.DAL.Model.Project", b =>
                {
                    b.HasOne("Simurgh.DAL.Model.Client", "Client")
                        .WithMany("Projects")
                        .HasForeignKey("ClientId");
                });
#pragma warning restore 612, 618
        }
    }
}
